require: rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.4.0
  NewCops: enable
  Exclude:
    - 'lib/generators/rails/templates/**/*'

RSpec/NamedSubject:
  Enabled: false
